name = "shop-quynh-baby"
main = ".wrangler/functions-build/index.js"
compatibility_date = "2026-06-09"
keep_vars = true

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*", "/admin", "/admin/*"]

[[d1_databases]]
binding = "DB"
database_name = "quynh-baby-shop"
database_id = "7822edac-5dad-451c-a57d-a9e9850fc9d4"

[[r2_buckets]]
binding = "PRODUCT_IMAGES"
bucket_name = "product-images"

[[r2_buckets]]
binding = "TRY_ON_IMAGES"
bucket_name = "try-on-images"
